### ISSUE TITLE
the nobs should be 10**2

### ISSUE THREAD

**Issue by wyfoffice** [david-cortes/cmfrec#1]
as the nusers = 10**2 and nitems = 10**2, the ratings should be the same as their length.

**Comment by david-cortes** [comment]
Thanks for spotting that! corrected the example now. Although, even though they should indeed have the same length, one still needs to specify an upper bound on the maximal ID when generating random numbers, and that was the purpose of the `nusers` and `nitems` variables. Their size is then `nobs`.

**Comment by wyfoffice** [comment]
@david-cortes and when running your demo, it also raise an error:


  File "/home/i2/桌面/recommendation_sys/cmfrec.py", line 38, in <module>
    recommender.topN_cold(attributes=np.random.normal(size=item_dim), n=10)

  File "/home/i2/.local/lib/python3.6/site-packages/cmfrec/__init__.py", line 1787, in topN_cold
    assert attributes.shape[0] == self.C.shape[1]

AssertionError

**Comment by david-cortes** [comment]
Sorry, my bad! Corrected that in the example too.

**Comment by wyfoffice** [comment]
@david-cortes oh... now I know my first question is wrong... sorry for my stupid and thank you for your kind response!!!

**Comment by wyfoffice** [comment]
@david-cortes I understand now! Sorry for my late reply! Thank you so much for your kind help!

**Comment by wyfoffice** [comment]
@ another question about the parameters in CMF
we factorize the matrix R into         U(user) * V(item)
and matrix of user information into U * P
matrix of item information into         V * Q

So there should be 3 ks of each matrix factorization, but you give 4
I read your explanation on http://cmfrec.readthedocs.io/en/latest/,  but still feel confused.

k (int) – Number of common (shared) latent factors to use. 
Is this K means the k in U * V ?

k_main (int) – Number of additional (non-shared) latent factors to use for the ratings factorization.Ignored for the offsets model.                                   
I feel the K_main is the same as last K

k_user (int) – Number of additional (non-shared) latent factors to use for the user attributes factorization. Ignored for the offsets model.                                   
Is this K_user means the k in U * P?

k_item (int) – Number of additional (non-shared) latent factors to use for the item attributes factorization. Ignored for the offsets model.                                    
Is this K_item means the K in V * P?

I think the last two are correct, but the first two are what I really don't understand.

Thanks in advance.

**Comment by david-cortes** [comment]
There are 3 factorizations, and thus there can be up to 3 different numbers of factors, but the way this package sets those numbers is by having a base number (k) and adding additional ones for each factorization (k_main, k_user, k_item). So the number of factors for each matrix is:
* U: k + k_main + k_user
* V: k + k_main + k_item
* P: k+ k_user
* Q: k + k_item

However, for the factorization of R, only (k + k_main) factors are taken from U and V, while (k + k_user) factors are taken from U and P for factorizing the user matrix. From these, only k factors are shared between both factorizations.

**Comment by wyfoffice** [comment]
get it! thanks!

**Comment by wyfoffice** [comment]
one more question, it seems that in your example, the users in the user information matrix is not necessarily be equivalent to the users in the ratings matrix?

**Comment by david-cortes** [comment]
It doesn't necessarily have to be equivalent in the sense that it can have extra users without ratings, and doesn't need to have information for every single user for which there are ratings. See the IPython notebook example for more details.
