### ISSUE TITLE
get each item feature's importance

### ISSUE THREAD

**Issue by enjieli** [david-cortes/cmfrec#11]
David, I am wondering whether there is a way to get individual item feature importance in `OMF_explicit` model.  How should I go about it to get information on which item features are positively correlated with a given user and which ones are negatively correlated?

Here are some simulated data:

```python
import numpy as np, pandas as pd
from cmfrec import OMF_explicit

n_users = 40
n_items = 50
n_ratings = 2000
n_user_attr = 4
n_item_attr = 50


np.random.seed(1)
ratings = pd.DataFrame({
    "UserId" : np.random.randint(n_users, size=n_ratings),
    "ItemId" : np.random.randint(n_items, size=n_ratings),
    "Rating" : np.random.normal(loc=3., size=n_ratings)
})
item_info = pd.DataFrame(np.random.normal(size = (n_items, n_item_attr)))
item_info["ItemId"] = np.arange(n_items)

model = OMF_explicit(k=5)
model.fit(ratings, I=item_info)
```

I assume I can get decomposed item embeddings this way:
```python
model.item_factors_cold(item_info.drop(columns=(['ItemId']))[1])
```

Is there a way to get more details on item feature importance?

Thanks!

**Comment by david-cortes** [comment]
It's not possible, because those are determined from linear combinations of the item attributes (each factor has different coefficients for each item attribute, those are under `model.D_`).

**Comment by enjieli** [comment]
i see. Got it. Thanks a lot!
