### ISSUE TITLE
Can't install. ERROR: Could not build wheels for cmfrec which use PEP 517 and cannot be installed directly

### ISSUE THREAD

**Issue by zihaohe123** [david-cortes/cmfrec#12]
File "/mnt/tmp/pip-install-jhlsso6h/cmfrec/setup.py", line 7, in <module>
    creating build/temp.linux-x86_64-3.6/cmfrec
    creating build/temp.linux-x86_64-3.6/src
    compile options: '-D_FOR_PYTHON -DUSE_DOUBLE -DHAS_MKL -DNO_CBLAS_HEADER -I/home/hadoop/miniconda3/envs/py36/lib/python3.6/site-packages/numpy/core/include -Isrc -I/home/hadoop/miniconda3/envs/py36/lib/python3.6/site-packages/findblas/ -I/home/hadoop/miniconda3/envs/py36/include/python3.6m -c'
    extra options: '-O3 -fopenmp -march=native -std=c99'
    gcc: src/collective.c
    gcc: cmfrec/cfuns_double.c
    gcc: src/common.c
    gcc: src/offsets.c
    In file included from src/collective.c:57:0:
    src/cmfrec.h:72:14: fatal error: omp.h: No such file or directory
         #include <omp.h>
                  ^~~~~~~
    compilation terminated.
    In file included from src/offsets.c:188:0:
    src/cmfrec.h:72:14: fatal error: omp.h: No such file or directory
         #include <omp.h>
                  ^~~~~~~
    compilation terminated.
    gcc: src/helpers.c
    gcc: src/lbfgs.c
    In file included from src/common.c:58:0:
    src/cmfrec.h:72:14: fatal error: omp.h: No such file or directory
         #include <omp.h>
                  ^~~~~~~
    compilation terminated.
    gcc: src/cblas_wrappers.c
    creating build/temp.linux-x86_64-3.6/cmfrec
    creating build/temp.linux-x86_64-3.6/src
    compile options: '-D_FOR_PYTHON -DUSE_DOUBLE -DHAS_MKL -DNO_CBLAS_HEADER -I/home/hadoop/miniconda3/envs/py36/lib/python3.6/site-packages/numpy/core/include -Isrc -I/home/hadoop/miniconda3/envs/py36/lib/python3.6/site-packages/findblas/ -I/home/hadoop/miniconda3/envs/py36/include/python3.6m -c'
    extra options: '-O3 -fopenmp -march=native -std=c99'
    gcc: src/collective.c
    gcc: cmfrec/cfuns_double.c
    gcc: src/common.c
    gcc: src/offsets.c
    In file included from src/collective.c:57:0:
    src/cmfrec.h:72:14: fatal error: omp.h: No such file or directory
         #include <omp.h>
  gcc: src/common.c
  In file included from src/offsets.c:188:0:
  src/cmfrec.h:72:14: fatal error: omp.h: No such file or directory
       #include <omp.h>
                ^~~~~~~
  compilation terminated.
  In file included from src/collective.c:57:0:
  src/cmfrec.h:72:14: fatal error: omp.h: No such file or directory
       #include <omp.h>
                ^~~~~~~
  compilation terminated.
  In file included from src/common.c:58:0:
  src/cmfrec.h:72:14: fatal error: omp.h: No such file or directory
       #include <omp.h>
                ^~~~~~~
  gcc: src/helpers.c
  compilation terminated.
  gcc: src/lbfgs.c
  gcc: src/cblas_wrappers.c
  In file included from /mnt/tmp/pip-build-env-f18wyvyi/overlay/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1832:0,
                   from /mnt/tmp/pip-build-env-f18wyvyi/overlay/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                   from /mnt/tmp/pip-build-env-f18wyvyi/overlay/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                   from cmfrec/cfuns_double.c:599:
  /mnt/tmp/pip-build-env-f18wyvyi/overlay/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it with " \
    ^~~~~~~
  In file included from src/helpers.c:57:0:
  src/cmfrec.h:72:14: fatal error: omp.h: No such file or directory
       #include <omp.h>
                ^~~~~~~
  In file included from src/cblas_wrappers.c:57:0:
  src/cmfrec.h:72:14: fatal error: omp.h: No such file or directory
       #include <omp.h>
                ^~~~~~~
  compilation terminated.
  compilation terminated.
  In file included from src/arithmetic_ansi.h:30:0,
                   from src/lbfgs.c:89:
  src/cmfrec.h:72:14: fatal error: omp.h: No such file or directory
       #include <omp.h>
                ^~~~~~~
  compilation terminated.
  In file included from cmfrec/cfuns_double.c:601:0:
  src/cmfrec.h:72:14: fatal error: omp.h: No such file or directory
       #include <omp.h>
                ^~~~~~~
  compilation terminated.
  /mnt/tmp/pip-build-env-f18wyvyi/overlay/lib/python3.6/site-packages/findblas/distutils.py:78: UserWarning: No CBLAS headers were found - function propotypes might be unreliable.
    warnings.warn(warning_msg)
  /mnt/tmp/pip-build-env-f18wyvyi/overlay/lib/python3.6/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /mnt/tmp/pip-install-zk41hzuo/cmfrec/cmfrec/cfuns_double.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  /mnt/tmp/pip-build-env-f18wyvyi/overlay/lib/python3.6/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /mnt/tmp/pip-install-zk41hzuo/cmfrec/cmfrec/cfuns_float.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  error: Command "gcc -pthread -B /home/hadoop/miniconda3/envs/py36/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -D_FOR_PYTHON -DUSE_DOUBLE -DHAS_MKL -DNO_CBLAS_HEADER -I/mnt/tmp/pip-build-env-f18wyvyi/overlay/lib/python3.6/site-packages/numpy/core/include -Isrc -I/mnt/tmp/pip-build-env-f18wyvyi/overlay/lib/python3.6/site-packages/findblas/ -I/home/hadoop/miniconda3/envs/py36/include/python3.6m -c src/offsets.c -o build/temp.linux-x86_64-3.6/src/offsets.o -O3 -fopenmp -march=native -std=c99" failed with exit status 1

ERROR: Failed building wheel for cmfrec
Failed to build cmfrec
ERROR: Could not build wheels for cmfrec which use PEP 517 and cannot be installed directly

**Comment by david-cortes** [comment]
You need the OpenMP modules for GCC - this is the standard module for multi-threading computing. Alternatively, you can edit the `setup.py` file, removing the entries saying `'-fopenmp'` from the python lists where they appear, but if you do so, it will work single-threaded only.

**Comment by zihaohe123** [comment]
Thanks for you reply! Actually the GCC version of my system is 7.2.1 and it has OpenMP features configured with it. Maybe I need to try the second solution. However, could you share with the modified the setup.py file with '-fopenmp' entries removed?

**Comment by david-cortes** [comment]
Attached is the modified `setup.py` file.

But in any case, you can see this from the message:
```
src/cmfrec.h:72:14: fatal error: omp.h: No such file or directory
     #include <omp.h>
              ^~~~~~~
compilation terminated.
```
which means either you are not using the gcc version that you think is being called (conda also provides its own gcc as a package btw), or your gcc installation somehow put the headers in the wrong system folder.

Are you trying to install this on a BSD system? I know those tend to put files in places where compilers later don't find them without forcibly specifying the paths.

[setup.zip](https://github.com/david-cortes/cmfrec/files/4725152/setup.zip)

**Comment by zihaohe123** [comment]
Thanks. I still can't figure out how i can tackle the OpenMP problem. I am not using a BSD system. It didn't work on my Mac or the CentOS server,  whether using conda or system python. I wonder if installing cmfrec needs some specific pre-configurations. Nevertheless, using the new setup.py file did help.

**Comment by david-cortes** [comment]
It doesn't need any specific pre-configuration. However, if you are on mac, it will likely come **without** OpenMP unless you manually install it. On CentOS it should work just fine - at least it doesn't require anything other than package `gcc` when installed on debian, opensuse, ubuntu, or freebsd (this last one also needs to install some of the required python packages from the package manager).

**Comment by zihaohe123** [comment]
Thanks David. I finally fixed it on my CentOS. It was because multiple versions of gcc were installed and I uninstalled one of them.
