### ISSUE TITLE
from . import wrapper_double, wrapper_float

### ISSUE THREAD

**Issue by tomorrow1weak2up** [david-cortes/cmfrec#14]
import cmfrec
  File "D:\Python3.7\lib\site-packages\cmfrec\__init__.py", line 1, in <module>
    from . import wrapper_double, wrapper_float
ImportError: DLL load failed: 找不到指定的模块。

in python 3.7.9, win10, pycharm

**Comment by david-cortes** [comment]
This package contains an extension with compiled code. If you want to run it without installing, you have to build it first:
```
python setup.py build_ext --inplace --force
```

**Comment by tomorrow1weak2up** [comment]
sorry, i get an error when "from cmfrec import CMF_explicit", shows above. I install cmfrec by pip and i get wrapper_double.cp37-win_amd64.pyd and wrapper_float.cp37-win_amd64.pyd under my folder "D:\Python3.7\Lib\site-packages\cmfrec".

**Comment by tomorrow1weak2up** [comment]
> This package contains an extension with compiled code. If you want to run it without installing, you have to build it first:
> 
> ```
> python setup.py build_ext --inplace --force
> ```

sorry, where is the setup.py, and if i run it with installing, how can i do it? thank you.

**Comment by david-cortes** [comment]
I don't know then. Try running python without pycharm from `D:\Python3.7\Lib\site-packages` and see if it works there, or from your home folder (e.g. open the command line, type 'python' and then `from cmfrec import CMF_explicit`).

The `setup.py` is in the repository, but will not be available and is not needed if you install the package.

**Comment by tomorrow1weak2up** [comment]
> I don't know then. Try running python without pycharm from `D:\Python3.7\Lib\site-packages` and see if it works there, or from your home folder (e.g. open the command line, type 'python' and then `from cmfrec import CMF_explicit`).
> 
> The `setup.py` is in the repository, but will not be available and is not needed if you install the package.

I import it from cmd, and so sad ,the same error, I'll find out how to fix it.

**Comment by david-cortes** [comment]
Then perhaps you have different python versions installed and the one that launches with `python` is different than the one that launches with `pip`.

**Comment by david-cortes** [comment]
Come to think about it, this is something that might happen if you install this package through pip (using PEP517) without having numpy/scipy already installed in the same venv.
