### ISSUE TITLE
about topN_cold function

### ISSUE THREAD

**Issue by tomorrow1weak2up** [david-cortes/cmfrec#15]
hi, Mr david cortes,  i notes that the topN_cold function in cmfrec package allow
"U (array(p,), or None) – User attributes in the new data (1-row only). Should only pass one of ‘U’ or ‘U_col’+’U_val’.
U_bin (array(p_bin,)) – User binary attributes in the new data (1-row only). Missing entries should have value np.nan. Only supported with", does it mean this function can only make cold-start recommendation for one user per time?

**Comment by david-cortes** [comment]
Yes, that's correct - the function works with only one user at a time. If  you're looking at parallelization, you can check `joblib` or similar.

**Comment by tomorrow1weak2up** [comment]
ok, thanks a lot.
