### ISSUE TITLE
CMF_implicit AssertionError

### ISSUE THREAD

**Issue by tomorrow1weak2up** [david-cortes/cmfrec#16]
cmf_model = CMF_implicit(k=100, w_main=0.3, w_user=0.7, lambda_=1e1, niter=50).fit(X=ratings_train_implicit, U=user_side_info.loc[user_side_info.UserId.isin(users_train)],
                                                            I=item_sideinfo_pca.loc[item_sideinfo_pca.ItemId.isin(ratings_train.ItemId.unique())])

I get a     assert "Value" in X.columns.values
AssertionError

**Comment by david-cortes** [comment]
If you pass a `DataFrame` as "X", it needs to have a column named "Value" for the implicit model. If you took the notebook example, that should be the column "Rating", which you need to rename.
