### ISSUE TITLE
Can I speed up the optimization process using GPU?

### ISSUE THREAD

**Issue by wyfoffice** [david-cortes/cmfrec#2]
As the optimization is based on tensorflow, I wonder if I can try to use GPU to speed up it

**Comment by david-cortes** [comment]
I don't think so. The optimizer used is the L-BFGS from SciPy, which doesn't use GPUs or cuda or anything like that. I'm not sure how it works internally though, and you might get some speed-up from the matrix multiplications (which are not a bottleneck here) depending on whether your tensorflow is linked against GPU blas libraries (e.g. cublas) - that's something you'd have to try and I'd be interested in seeing some comparisons before/after.

Nevertheless, if you know tensorflow, you can also take a look at the source code and change the optimizer to something else from tensorflow's own implementations that would support GPU acceleration, but you'll probably have a hard time having it find good local optima.

**Comment by wyfoffice** [comment]
okay... 
Thanks a lot for your reply~~
