### ISSUE TITLE
swap_users_and_items  - unexpected keyword argument 'scale_lam' 

### ISSUE THREAD

**Issue by Rickitik** [david-cortes/cmfrec#24]
When i try to swap users and items i always get an error:

model = CMF_implicit(use_cg=True, w_main=0.7, w_user=10.0, w_item=25.0, 
                     finalize_chol=False, k=100, lambda_=0.01, 
                     niter=15, use_float=True)
model.fit(X=coo, U=A_coo, I=B_coo)
model.swap_users_and_items()

TypeError: __init__() got an unexpected keyword argument 'scale_lam'

**Comment by david-cortes** [comment]
Thanks for the bug report. Should be fixed now:
```
pip install -U cmfrec
```
