### ISSUE TITLE
name 'n' is not defined when using CMF_implicit()

### ISSUE THREAD

**Issue by alirezagharahi** [david-cortes/cmfrec#29]
Hi,

I used the "CMF_implict" model and tried to recommend users to new items using "predict_new()" function but I got the following error:
```
__init__.py", line 2178, in _factors_cold_multiple
    n, m_u, 0,
NameError: name 'n' is not defined
```
Here I do not know what "n" is referring to? is it number of users or items or number of cold items?

**Comment by david-cortes** [comment]
Thanks for the bug report. Should be fixed now in the latest version:
```
pip install -U cmfrec
```
