### ISSUE TITLE
where can I find the demographic info data?

### ISSUE THREAD

**Issue by wyfoffice** [david-cortes/cmfrec#3]
As your jupyter notebook codes shows in part 2.4 
http://nbviewer.jupyter.org/github/david-cortes/cmfrec/blob/master/example/cmfrec_movielens_sideinfo.ipynb#p24
the zipcode_abbs is imported from a csv file called states.csv, however, I cannot find this data in your link. would you please share me a link for this data?
Many thanks!!

**Comment by david-cortes** [comment]
See the links at the beginning of section 2:
http://federalgovernmentzipcodes.us/
http://www.fonz.net/blog/archives/2008/04/06/csv-of-states-and-state-abbreviations/

**Comment by wyfoffice** [comment]
thanks a lot for your kind help!
