### ISSUE TITLE
predict_new() for OMF: name 'glob_mean' is not defined

### ISSUE THREAD

**Issue by alirezagharahi** [david-cortes/cmfrec#30]
Hi,

I am using the OMF model to recommend users to cold-items. When calling the predict_new() on the trained OMF model I got the following error:

 B = self._factors_cold_multiple(U=I, is_I=True)
  File "/python3.7/site-packages/cmfrec/__init__.py", line 5961, in _factors_cold_multiple
    glob_mean,
NameError: name 'glob_mean' is not defined

**The same code perfectly works for CMF model.**

**Comment by david-cortes** [comment]
Thanks for the bug report. Should be fixed now:
```
pip install -U cmfrec
```
