### ISSUE TITLE
ERROR: Invalid parameter combination, for fitting OMF

### ISSUE THREAD

**Issue by alirezagharahi** [david-cortes/cmfrec#31]
Hi,

I got the following error when I fit an OMF model OMF.fit(X=interaction_matrix, I=item_features):

File "cmfrec/wrapper_untyped.pxi", line 1685, in cmfrec.wrapper_double.call_fit_offsets_implicit_als
ValueError: Invalid parameter combination.

I can fit CMF model with the same input but it does not work for OMF

**Comment by david-cortes** [comment]
That's just what it says: not all combinations of possible input parameters/arguments are supported. CMF and OMF are different models which follow different optimization routes and what works for one might not work adequately for the other.
