### ISSUE TITLE
topN function for C API

### ISSUE THREAD

**Issue by ankane** [david-cortes/cmfrec#32]
Hey @david-cortes, I'm working on updating the cmfrec [Ruby library](https://github.com/ankane/cmfrec-ruby) to 3.4.2 and noticed the `topN` function is no longer exported. Is there a better method to use for it? From what I can tell, the Python and R libraries still use it, so may be good to add `CMFREC_EXPORTABLE` to export it as part of the C API ([relevant code](https://github.com/david-cortes/cmfrec/blob/68ee6dda5d11fc804da12cc3a0df94d01d5e1c38/src/cmfrec.h#L1158-L1169)).

**Comment by david-cortes** [comment]
It was replaced with specialized functions for each model, such as `topN_old_collective_explicit` or `topN_new_collective_explicit`. I haven't updated much the Cython part of the Python interface, but the R interface doesn't use `topN`.

**Comment by ankane** [comment]
Great, will check them out. Thanks!

Also, fwiw, updated the IsoTree and OutlierTree Ruby libraries to use the latest C++ versions yesterday 🎉
