### ISSUE TITLE
Implicit feedback or explicit feedback

### ISSUE THREAD

**Issue by nicky258irl** [david-cortes/cmfrec#35]
Hi, I would like to know whether 'click' should be considered explicit feedback or implicit feedback here?
Your answer will be appreciated.

**Comment by david-cortes** [comment]
Statistical and mathematical software usually come with associated references that explore this type of questions. For example, a quick look at the docs here would point you to this article:

> Hu, Yifan, Yehuda Koren, and Chris Volinsky. “Collaborative filtering for implicit feedback datasets.” 2008 Eighth IEEE International Conference on Data Mining. Ieee, 2008.
