### ISSUE TITLE
Getting different scores with using predict_new and predict methods

### ISSUE THREAD

**Issue by Jiaqi-ads** [david-cortes/cmfrec#36]
Hi David,

I was doing some experiments on the Movie-lens data and realised that the predicted scores obtained through the model.predict_new and model.predict are quite different from each other, even for the same user and item. And in general, the scores obtained through predict_new on average are much lower than the ones obtained through predict. Any ideas on why this may occur? Thanks!

In the screenshot, the r1_scores are produced by the model.predict method and r2_scores are produced by the model.predict_new. All of the items are in the training dataset.

 
![image](https://user-images.githubusercontent.com/109973944/200114917-f33ede40-e2f3-454a-807d-544a7ad72f2f.png)

**Comment by david-cortes** [comment]
This is the correct behavior: `predict_new` is based only on side information from the items, while `predict` is based on interactions data + side information if available.
