### ISSUE TITLE
Upstream prematurely closing connection on nginx when using topN method

### ISSUE THREAD

**Issue by jemarder** [david-cortes/cmfrec#37]
I'm trying to use cmfrec in a Docker container deployed on AWS using Sagemaker. The container implements a gunicorn server with nginx to respond to inference requests at the Sagemaker endpoint. When testing locally using the Docker container everything appears to run fine - I get predictions and no errors. However, when uploading to AWS and performing inference I get the following error in the logs:

`[error] 11#11: *1819 upstream prematurely closed connection while reading response header from upstream, client: xxx.xxx.xxx.2, server: , request: "POST /invocations HTTP/1.1", upstream: "http://unix:/tmp/gunicorn.sock:/invocations", host: "xxx.xxx.xxx.2:8080"`

I have tried this with setting the ENV DONT_SET_MARCH=1 as well as without specifying that prior to installing cmfrec in the Docker container. It is using an Ubuntu 18.04 image.

This happens when using the topN method with the trained model. The suggested solutions from AWS are to reduce the latency of the algorithm or increase the container's timeout limit. Increasing the timeout settings did not help in this case. 

Please let me know if you have any suggestions.

Thank you for the help.

**Comment by david-cortes** [comment]
That's a bug with GNU's `libgomp` not working with gunicorn, not with this library. You can google about it for more info. As a workaround, you can try disabling multithreading.

**Comment by jemarder** [comment]
Thanks for the quick response!
