### ISSUE TITLE
How to predict items for new users based on a implicit CMFREC Model? (R)

### ISSUE THREAD

**Issue by DanielRauser** [david-cortes/cmfrec#39]
Hello,

I'm currently building a recommender system that uses implicit feedback data. Now I want to use the built model to predict the instances in the test data. But I get an error-code:

![image](https://user-images.githubusercontent.com/73906842/203513121-086085a5-80c8-4d4b-90ab-773f81a1666e.png)

Also I don't quite understand how to predict the TopN-items for multiple instances. With the TopN-function it seems to be only possible to predict the Top-N-items for one user. Is that assumption right? Or if not how do I use the the dataset which includes [SessionID, material_number, Score] to predict the topN-Items for each session?

I really would appreciate help. Thanks in advance,

Daniel 
```{r}

X <- as.coo.matrix(Matrix_model_4@data)

reco_split <- create.reco.train.test(
    X,
    users_test_fraction = 0.2,
    items_test_fraction = 0.3,
    min_pos_test = 2,
    seed = 123
)

X_train <- reco_split$X_train ## Train data for test users
X_test <- reco_split$X_test ## Test data for test users
X_rem <- reco_split$X_rem ## Data to fit the model
users_test <- reco_split$users_test ## IDs of the test users

### Random recommendations (random latent factors)
set.seed(123)
UserFactors_random <- matrix(rnorm(nrow(X_test) * 5), nrow=5)
ItemFactors_random <- matrix(rnorm(ncol(X_test) * 5), nrow=5)

### Non-personalized recommendations
model_baseline <- cmfrec::MostPopular(as.coo.matrix(X_rem), implicit=TRUE)
item_biases <- model_baseline$matrices$item_bias


model_iALS <- CMF_implicit(as.coo.matrix(X_rem), k=16, lambda = 0.1, alpha = 0.01, niter = 16L)

pred_iALS <- predict(model_wrmf, X_test)

```

**Comment by david-cortes** [comment]
In your screenshot, it looks like you haven't loaded the library with `library(cmfrec)`. In the example code, looks like you are passing a different object at the end.

This library doesn't do multiple topN predictions btw.

**Comment by DanielRauser** [comment]
Hello, 

sorry for the mistake. Here you see the fixed code. But I still have an error message. 

Best regards,

Daniel


```{r}

library(cmfrec)

X <- as.coo.matrix(Matrix_model_4@data)

reco_split <- create.reco.train.test(
    X,
    users_test_fraction = 0.2,
    items_test_fraction = 0.3,
    min_pos_test = 2,
    seed = 123
)

X_train <- reco_split$X_train ## Train data for test users
X_test <- reco_split$X_test ## Test data for test users
X_rem <- reco_split$X_rem ## Data to fit the model
users_test <- reco_split$users_test ## IDs of the test users

### Random recommendations (random latent factors)
set.seed(123)
UserFactors_random <- matrix(rnorm(nrow(X_test) * 5), nrow=5)
ItemFactors_random <- matrix(rnorm(ncol(X_test) * 5), nrow=5)

### Non-personalized recommendations
model_baseline <- cmfrec::MostPopular(as.coo.matrix(X_rem), implicit=TRUE)
item_biases <- model_baseline$matrices$item_bias


model_iALS <- CMF_implicit(as.coo.matrix(X_rem), k=16, lambda = 0.1, alpha = 0.01, niter = 16L)

pred_iALS <- predict(model_iALS, X_test)

```

![image](https://user-images.githubusercontent.com/73906842/203523874-6865769f-9fc2-4833-8169-55b6a8803ae7.png)

**Comment by david-cortes** [comment]
It looks like you're trying to pass a `dgRMatrix` to `predict`, which is not supported (only `dgTMatrix`). You can check the docs for more details. It also looks like you are using an older version of this package as I'd see a different error if I try to execute your code.
