### ISSUE TITLE
R Session aborted

### ISSUE THREAD

**Issue by naggefreschle** [david-cortes/cmfrec#41]
In R Studio I receive the notification "R Session Aborted" when runnung ContentBased()
Additionally it shows:
```
Error in .ContentBased(inputs$processed_X, inputs$processed_U, inputs$processed_I, :
BLAS/LAPACK routine 'DLASCLS' gave error code -4
```
dim(X): 6043 2416
dim(U): 6038 4
dim(I): 2416 13

**Comment by david-cortes** [comment]
Thanks for the bug report. Will fix this soon, but in the meantime: calling `ContentBased` requires having the same number of rows in X and U, without padding either with NAs to accommodate the other.

**Comment by david-cortes** [comment]
Now it should (a) avoid aborting the R session when something like this fails; (b) throw an informative message if the data is not suitable for default option `start_with_ALS=TRUE`.

To install the latest version from github:
```r
remotes::install_github("david-cortes/cmfrec")
```

**Comment by naggefreschle** [comment]
I already saw the problem with different dimensions and fixed it.
I still receive the error about DLASCLS. Where is this coming from?
Rstudio is not aborting anymore

**Comment by david-cortes** [comment]
Thanks for the update. I've now expanded a bit the docs to add that option `start_with_ALS=TRUE` can lead to errors like this. If you are observing this error, you might probably need to pass `start_with_ALS=FALSE` and increase the number of iterations (`maxiter`), although it might be a symptom that there is something wrong with your data (e.g. empty or duplicate users/items).
