### ISSUE TITLE
Error when installing cmfrec

### ISSUE THREAD

**Issue by ananv21** [david-cortes/cmfrec#45]
Hello,

When I try to install cmfrec via pip, I get the following error:

**error: command 'gcc' failed: No such file or directory**

Why might this be happening?

**Comment by david-cortes** [comment]
> Hello,
> 
> When I try to install cmfrec via pip, I get the following error:
> 
> **error: command 'gcc' failed: No such file or directory**
> 
> Why might this be happening?

Highlight from the readme:
![image](https://github.com/david-cortes/cmfrec/assets/11860098/c5de89e2-fe13-4bda-a8dc-c493f4db6924)
