### ISSUE TITLE
Ranking metric for measuring the performance of the model with side info

### ISSUE THREAD

**Issue by jovanmei** [david-cortes/cmfrec#46]
Hi, I wanted to express my appreciation for the "cmfrec_movielens_sideinfo.ipynb" notebook, as I found it incredibly helpful and interesting. I would like to ask if you have some recommended method to leverage ranking metrics such as nDCG, recall, precision, and others for evaluating the Top-N rank list. Thanks!

**Comment by david-cortes** [comment]
> I would like to ask if you have some recommended method to leverage ranking metrics such as nDCG, recall, precision, and others for evaluating the Top-N rank list. Thanks!

You can try this package: https://github.com/david-cortes/recometrics

**Comment by jovanmei** [comment]
> > I would like to ask if you have some recommended method to leverage ranking metrics such as nDCG, recall, precision, and others for evaluating the Top-N rank list. Thanks!
> 
> You can try this package: https://github.com/david-cortes/recometrics

Thanks for the reply, I can measure it when the model not using the side information, and wanna ask how to change it to measure it for the model using the side information, thanks! here is the code:

```
model_cg = CMF_implicit(
    k=50, lambda_=5, niter=15, use_float=False,
    use_cg=True, finalize_chol=False,
    precompute_for_predictions=False,
    verbose=False
).fit(X=ratings_train,
      U=user_attr_train,
      I=item_attr_train)

metrics_cg = calc_reco_metrics(
    X_train.tocsr()[:X_test.shape[0],:X_test.shape[1]],
    X_test.tocsr(),
    model_cg.A_[:X_test.shape[0],:],
    model_cg.B_[:X_test.shape[1],:],
    k=10, all_metrics=True
)
```

but get the error:

```
[456](file:///D:/Workplace/Environment/anaconda3/envs/recsys_new/lib/site-packages/recometrics/__init__.py:456)     raise ValueError("Input matrices cannot be empty.")
    [457](file:///D:/Workplace/Environment/anaconda3/envs/recsys_new/lib/site-packages/recometrics/__init__.py:457) if A.shape[0] < X_test.shape[0]:
--> [458](file:///D:/Workplace/Environment/anaconda3/envs/recsys_new/lib/site-packages/recometrics/__init__.py:458)     raise ValueError("Number of users in 'A' and 'X_test' does not match.")
    [459](file:///D:/Workplace/Environment/anaconda3/envs/recsys_new/lib/site-packages/recometrics/__init__.py:459) if B.shape[0] < X_test.shape[1]:
    [460](file:///D:/Workplace/Environment/anaconda3/envs/recsys_new/lib/site-packages/recometrics/__init__.py:460)     raise ValueError("Number of items in 'B' and 'X_test' does not match.")

ValueError: Number of users in 'A' and 'X_test' does not match.
```

**Comment by david-cortes** [comment]
Have you checked that the `X_test` that you are passing there has the right number of entries? If the data is already ordered like that, it should match with what you'd get from this:
```python
X_train.tocsr()[X_test.shape[0]:,:X_test.shape[1]]
```

Otherwise, are you able to provide a reproducible example with random data?

**Comment by jovanmei** [comment]
> Have you checked that the `X_test` that you are passing there has the right number of entries? If the data is already ordered like that, it should match with what you'd get from this:
> 
> ```python
> X_train.tocsr()[X_test.shape[0]:,:X_test.shape[1]]
> ```
> 
> Otherwise, are you able to provide a reproducible example with random data?

Thanks for the reply, I have used the MovieLens 1M data that you provided in the "cmfrec_movielens_sideinfo.ipynb" notebook, but I changed the way to split the data,

```
ratings_train, ratings_test = train_test_split(ratings, test_size=0.2, random_state=123)
user_attr_train, user_attr_test = train_test_split(user_side_info, test_size=0.2, random_state=123)
item_attr_train, item_attr_test = train_test_split(item_sideinfo_pca, test_size=0.2, random_state=123)

def df_to_coo(df):
    X = coo_matrix((df.Rating, (df.UserId, df.ItemId)))
    X.row = X.row.astype(np.int32)
    X.col = X.col.astype(np.int32)
    X.data = X.data.astype(np.float64)
    return X

X_train = df_to_coo(ratings_train)
X_test = df_to_coo(ratings_test)
```

**Comment by david-cortes** [comment]
In your example, the IDs will not match because the movielens data doesn't follow base-0 indexing like scipy.

If you want it to work like that, you need to ensure that the matrix you are constructing has the right shape, for which you'll need to encode all the IDs to match them to rows.

**Comment by jovanmei** [comment]
> In your example, the IDs will not match because the movielens data doesn't follow base-0 indexing like scipy.
> 
> If you want it to work like that, you need to ensure that the matrix you are constructing has the right shape, for which you'll need to encode all the IDs to match them to rows.

Thanks! it works after the encoding :)
