### ISSUE TITLE
fail to use topN_cold

### ISSUE THREAD

**Issue by wyfoffice** [david-cortes/cmfrec#5]
I met a problem when using the method topN_cold, 
my user information dimension is 12, if I try to input numpy arrays that are different from 12, it raises 
AssertionError, 
which I know should be wrong. But when I input the numpy array that is in 12 digits, it raises

ValueError: all the input arrays must have same number of dimensions

here is how the rating matrix looks like

![image](https://user-images.githubusercontent.com/26210679/42988346-c20a9288-8c2e-11e8-93cb-0e4a62ae3df6.png)

and the user information matrix: there are 13 columns of user information, contains the user id
![image](https://user-images.githubusercontent.com/26210679/42988409-ef1baafa-8c2e-11e8-8e0a-2c1ae664f021.png)

also, I upload my jupyter notebook for you to have a detail look
[cmf with cold start-Copy1.zip](https://github.com/david-cortes/cmfrec/files/2212861/cmf.with.cold.start-Copy1.zip)

**Comment by david-cortes** [comment]
I'm sorry but I cannot see the error from the ipython notebook as it seems it failed earlier and didn't run all the code. Nevertheless, this could perhaps be caused by:
* Passing more than 1 user (or more than 1 row, with attributes for the same user).
* Some problem with pandas or numpy (please try using the latest versions if possible).

**Comment by wyfoffice** [comment]
sorry, I shall upload the jupyter notebook that shows the error
[cmf with cold start-Copy1.zip](https://github.com/david-cortes/cmfrec/files/2217711/cmf.with.cold.start-Copy1.zip)

**Comment by david-cortes** [comment]
Oops yeah that's an error there, will correct it later today - thanks for reporting it! In the meantime, you can pass `offsets_model=False` and it should work fine with it. Also just FYI, the parameters `cols_bin_user` and `cols_bin_item` are ignored when using `offsets_model=True`.

In the mean time, if you want to fix it yourself, you can go to line 1807 of `cmfrec/__init__.py` (if you're using anaconda and installed it with pip, this is typically under some path like `anaconda3/lib/python3.6/site-packages/`, and change it from:
`user_vec = attributes.reshape(1,-1).dot(self.C).astype(self.A.dtype)`
to:
`user_vec = attributes.reshape(1,-1).dot(self.C).astype(self.A.dtype).reshape(-1)`

**Comment by wyfoffice** [comment]
thanks! I will have a try!

**Comment by david-cortes** [comment]
Fixed the bug now in github and pip. Please install the latest version from pip (you might need to do a forced reinstalled or an update) and confirm that it's corrected.

**Comment by wyfoffice** [comment]
sure!
