### ISSUE TITLE
Can't reproduce results from recommender

### ISSUE THREAD

**Issue by y-hendrix** [david-cortes/cmfrec#6]
Every time I refit recommender on the same data set I get slightly different results. Using random_seed inside CMF definition does not solve the problem.  I am also including two outputs I get after refitting recommender. 

I am using 
cmfrec - Version: 0.5.2.2
tensorflow - Version: 1.9.0
numpy - Version: 1.14.3
pandas - Version:  0.23.0
python - 3.6.5
MacOS
Darwin-17.7.0-x86_64-i386-64bit'

## Bellow is the code with simulated data 
```python
import numpy as np
import pandas as pd
from cmfrec import CMF

## simulating some movie ratings
nusers = 10**2
nitems = 10**2
nobs = 10**2
np.random.seed(1)
ratings = pd.DataFrame({
	'UserId' : np.random.randint(nusers, size=nobs),
	'ItemId' : np.random.randint(nitems, size=nobs),
	'Rating' : np.random.randint(low=1, high=6, size=nobs)
	})

## random product side information
user_dim = 10
user_attributes = pd.DataFrame(np.random.normal(size=(nusers, user_dim)))
user_attributes['UserId'] = np.arange(nusers)
user_attributes = user_attributes.sample(int(nusers/2), replace=False)

item_dim = 5
item_attributes = pd.DataFrame(np.random.normal(size=(nitems, item_dim)))
item_attributes['ItemId'] = np.arange(nitems)
item_attributes = item_attributes.sample(int(nitems/2), replace=False)

## fitting a model and making some recommendations
recommender = CMF(k=20, k_main=3, k_user=2, k_item=1, reg_param=1e-4, random_seed=10)

recommender.fit(ratings=ratings, user_info=user_attributes, item_info=item_attributes,
	cols_bin_user=None, cols_bin_item=None)

recommender.predict(user=[0,0,1], item=[0,1,0])
```

## results I get for two runs on the same data set
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 0.014191
  Number of iterations: 456
  Number of functions evaluations: 472
Out[1318]: array([3.032462 , 3.3919058, 2.881726 ], dtype=float32) 

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 0.014157
  Number of iterations: 380
  Number of functions evaluations: 395
Out[1319]: array([3.207756 , 3.1969616, 2.9189765], dtype=float32)

**Comment by david-cortes** [comment]
Could you please run the following code two times and see if you get the same result:
```python
import tensorflow as tf
tf.reset_default_graph()
tf.set_random_seed(1234)
a = tf.random_uniform([1])
b = tf.random_normal([1])

# Repeatedly running this block with the same graph will generate the same
# sequences of 'a' and 'b'.
print("Session 1")
with tf.Session() as sess1:
  print(sess1.run(a))  # generates 'A1'
  print(sess1.run(a))  # generates 'A2'
  print(sess1.run(b))  # generates 'B1'
  print(sess1.run(b))  # generates 'B2'

print("Session 2")
with tf.Session() as sess2:
  print(sess2.run(a))  # generates 'A1'
  print(sess2.run(a))  # generates 'A2'
  print(sess2.run(b))  # generates 'B1'
  print(sess2.run(b))  # generates 'B2'
```

PS. when you post code in github, it can be formated as code by putting three backticks before and after, and also the name of the language for coloring, e.g.
````
```python
<your code>
```
````

**Comment by y-hendrix** [comment]
I do get the same results

**Comment by david-cortes** [comment]
Please try the code in the branch `randomseed` and see if results are reproducible now (you can download the file `__init__.py` from that branch and paste it in the path where the package is installed, which you can get through something like this: `import cmfrec;cmfrec.__file__`)

**Comment by y-hendrix** [comment]
I have rerun the results using randmoseed brunch and I still get the same inconstancies.
Here is the output for 3 runs:

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 0.014180
  Number of iterations: 349
  Number of functions evaluations: 359
Out[2047]: array([3.0952775, 3.4493449, 2.9370098], dtype=float32)

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 0.014258
  Number of iterations: 349
  Number of functions evaluations: 356
Out[2048]: array([2.835203 ,       nan, 2.8114781], dtype=float32)

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 0.014187
  Number of iterations: 375
  Number of functions evaluations: 383
Out[2049]: array([2.9186566, 3.309124 , 2.746409 ], dtype=float32)

**Comment by david-cortes** [comment]
Hmmm, that’s some really unexpected behavior. Both the `0.5.2.2` version and the `randomseed` version produce the same results for me, in windows and linux. I tried one more trick – this time the matrices are initialized in numpy rather than tensorflow, so it should be slower but guaranteed to be reproducible – please give it another try (it's in the branch `randomseed`).

Please also confirm that you see an additional print statement that I put there (it will print `”you are seeing this confirmation.”`).

**Comment by y-hendrix** [comment]
My mistake, I forgot to include deepcopy(). Yes, the results are the same now and I am seeing your ”you are seeing this confirmation.” message. It also prints "INFO:tensorflow:Optimization terminated with:" twice.  Thank you for looking into this.

```
recommender.fit(ratings=deepcopy(ratings), user_info=deepcopy(user_attributes), item_info=deepcopy(item_attributes),
	cols_bin_user=None, cols_bin_item=None)
```
## Output:
### run 1:
you are seeing this confirmation.
INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 0.014221
  Number of iterations: 349
  Number of functions evaluations: 355
INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 0.014221
  Number of iterations: 349
  Number of functions evaluations: 355
Out[2435]: array([2.9888248, 3.3993542, 2.8996358], dtype=float32)

### run 2:
you are seeing this confirmation.
INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 0.014221
  Number of iterations: 349
  Number of functions evaluations: 355
INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 0.014221
  Number of iterations: 349
  Number of functions evaluations: 355
Out[2436]: array([2.9888248, 3.3993542, 2.8996358], dtype=float32)
